# Generated by Django 5.0.1 on 2024-01-19 05:38

import auth_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(default=auth_api.models.rand_name, max_length=255),
        ),
    ]
